### ISSUE TITLE
RuntimeError: CluPSystem is not attached to a `Trainer`

### ISSUE THREAD

**Issue by liulian233** [altndrr/clup#1]
Hi, when I run "python -m cli clup  ./models/target/pretrained/swav-1000ep-FER2013-5000prototypes.ckpt   ./models/source/resnet18_rafdb-0.839.pt    fer2013  --epochs 50  --lr 0.1   --batch_size 32  --optimizer sgd  --optimizer_kw "{\"weight_decay\": 0.0005, \"momentum\": 0.9, \"nesterov\": true}"  --lr_scheduler cosine_annealing   --lr_scheduler_kw "{\"T_max\": 50}"  --mixup_alpha 0.2  --labeled_samples_mode purity  --labeled_samples_mode_kw "{\"num_prototypes\": 1000, \"drop_outliers\": false, \"iter_clusters\": 1}"  --labeled_samples_size 0.2", I encountered the following problems. How can I solve it？Thanks.

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/anaconda3/envs/yaoby/lib/python3.7/runpy.py:193 in _run_module_as_main                     │
│                                                                                                  │
│   190 │   if alter_argv:                                                                         │
│   191 │   │   sys.argv[0] = mod_spec.origin                                                      │
│   192 │   return _run_code(code, main_globals, None,                                             │
│ ❱ 193 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   194                                                                                            │
│   195 def run_module(mod_name, init_globals=None,                                                │
│   196 │   │   │      run_name=None, alter_sys=False):                                            │
│                                                                                                  │
│ /root/anaconda3/envs/yaoby/lib/python3.7/runpy.py:85 in _run_code                                │
│                                                                                                  │
│    82 │   │   │   │   │      __loader__ = loader,                                                │
│    83 │   │   │   │   │      __package__ = pkg_name,                                             │
│    84 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  85 │   exec(code, run_globals)                                                                │
│    86 │   return run_globals                                                                     │
│    87                                                                                            │
│    88 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/cli/__main__.py:53 in <module>                                   │
│                                                                                                  │
│   50 │   │   │   command = COMMANDS.get(key)                                                     │
│   51 │   │   │   if command and value:                                                           │
│   52 │   │   │   │   cmd = command(options, console)                                             │
│ ❱ 53 │   │   │   │   cmd.run()                                                                   │
│   54 │   │   │   │   executed = True                                                             │
│   55 │   │   │   │   break                                                                       │
│   56                                                                                             │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/cli/commands/clup.py:152 in run                                  │
│                                                                                                  │
│   149 │   │   │   criterion=criterion,                                                           │
│   150 │   │   │   pseudo_labeling_mode=self.options.get("labeled_samples_mode"),                 │
│   151 │   │   │   pseudo_labeling_mode_kw=self.options.get("labeled_samples_mode_kw", {}),       │
│ ❱ 152 │   │   │   **self.options,                                                                │
│   153 │   │   )                                                                                  │
│   154 │   │                                                                                      │
│   155 │   │   # If required, freeze part of the system.                                          │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/src/systems/clup.py:29 in __init__                               │
│                                                                                                  │
│    26 │   │   labeled_samples: Optional[List[int]] = None,                                       │
│    27 │   │   **kwargs,                                                                          │
│    28 │   ) -> None:                                                                             │
│ ❱  29 │   │   super().__init__(model, *args, pseudo_every=1, **kwargs)  #                        │
│    30 │   │   self.labels = labels                                                               │
│    31 │   │   self.labeled_samples: List[int] = labeled_samples or []                            │
│    32 │   │   self.train_criterion = self.criterion                                              │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/src/systems/classification.py:39 in __init__                     │
│                                                                                                  │
│    36 │   │   :param lr: learning rate of the system                                             │
│    37 │   │   :param lr_scheduler: learning rate policy for training                             │
│    38 │   │   """                                                                                │
│ ❱  39 │   │   super().__init__(model, *args, **kwargs)                                           │
│    40 │   │                                                                                      │
│    41 │   │   self.criterion: Module = torch.nn.CrossEntropyLoss()                               │
│    42 │   │   if criterion:                                                                      │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/src/systems/base.py:29 in __init__                               │
│                                                                                                  │
│    26 │                                                                                          │
│    27 │   # def __init__(self, model: Type[BaseModel], **kwargs) -> None:                        │
│    28 │   def __init__(self, model, **kwargs) -> None:                                           │
│ ❱  29 │   │   super().__init__()                                                                 │
│    30 │   │                                                                                      │
│    31 │   │   self.kwargs = kwargs                                                               │
│    32 │   │   self.save_hyperparameters(kwargs)                                                  │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/src/systems/mixins/pseudo_labelling.py:20 in __init__            │
│                                                                                                  │
│    17 │   """Implementation of a mixin for pseudo labelling."""                                  │
│    18 │                                                                                          │
│    19 │   def __init__(self, *args, **kwargs) -> None:                                           │
│ ❱  20 │   │   super().__init__(*args, **kwargs)                                                  │
│    21 │   │   self.pseudo_labels: Tensor                                                         │
│    22 │   │   self.pseudo_labels_confidence: Tensor                                              │
│    23 │   │   self.pseudo_every = kwargs.get("pseudo_every", 10)                                 │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/src/systems/mixins/mixup.py:13 in __init__                       │
│                                                                                                  │
│   10 │   """Implementation of a mixin for mixup."""                                              │
│   11 │                                                                                           │
│   12 │   def __init__(self, *args, **kwargs) -> None:                                            │
│ ❱ 13 │   │   super().__init__(*args, **kwargs)                                                   │
│   14 │   │   self.mixup_alpha = kwargs.get("mixup_alpha", -1)                                    │
│   15 │   │   self.mixup_last_lambda = -1                                                         │
│   16                                                                                             │
│                                                                                                  │
│ /home/adminroot/user/yaoby/clup/src/systems/mixins/base.py:26 in __init__                        │
│                                                                                                  │
│   23 │   │   if not hasattr(self, "current_epoch"):                                              │
│   24 │   │   │   self.current_epoch: int                                                         │
│   25 │   │                                                                                       │
│ ❱ 26 │   │   if not hasattr(self, "trainer"):                                                    │
│   27 │   │   │   self.trainer: Optional["pl.Trainer"] = None                                     │
│   28                                                                                            │
│                                                                                                  │
│ /root/anaconda3/envs/yaoby/lib/python3.7/site-packages/pytorch_lightning/core/module.py:207 in   │
│ trainer                                                                                          │
│                                                                                                  │
│    204 │   │   if self._fabric is not None:                                                      │
│    205 │   │   │   return _TrainerFabricShim(fabric=self._fabric)  # type: ignore[return-value]  │
│    206 │   │   if not self._jit_is_scripting and self._trainer is None:                          │
│ ❱  207 │   │   │   raise RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Tra  │
│    208 │   │   return self._trainer  # type: ignore[return-value]                                │
│    209 │                                                                                         │
│    210 │   @trainer.setter                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CluPSystem is not attached to a `Trainer`.

**Comment by altndrr** [comment]
Hi, based on the error message, it appears that there are references to Fabric objects in the Lightning library. If I recall correctly, these references were introduced in version 2.0, which our code was not tested with. Could you please check the versions of your installed packages and share them with me below?

**Comment by liulian233** [comment]
The packages are blow. What should I do?
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
audioread                 3.0.0                    pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.01.10           h06a4308_0
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7        py37h06a4308_0
cffi                      1.15.1           py37h5eee18b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
cryptography              39.0.1           py37h9ce1e76_0
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
facenet-pytorch           2.5.3                    pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
google-auth               2.18.1                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
idna                      3.4              py37h06a4308_0
imageio                   2.28.1                   pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
jpeg                      9e                   h5eee18b_1
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lazy-loader               0.2                      pypi_0    pypi
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_0
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.2                h7f8727e_0
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0
librosa                   0.8.1                    pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
lightning-utilities       0.8.0                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
metrics                   0.3.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py37h7f8727e_0
mkl_fft                   1.3.1            py37hd3c417c_0
mkl_random                1.2.2            py37h51133e4_0
msgpack                   1.0.5                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
munch                     2.5.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  2.6.3                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.21.5           py37h6c91a56_3
numpy-base                1.21.5           py37ha15fc14_3
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1t               h7f8727e_0
packaging                 23.1                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pathlib2                  2.3.7.post1              pypi_0    pypi
pathspec                  0.5.5                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    9.4.0            py37h6a678d5_0
pip                       22.3.1           py37h06a4308_0
pooch                     1.6.0                    pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.15.1                   pypi_0    pypi
pyopenssl                 23.0.0           py37h06a4308_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1                    py37_1
python                    3.7.16               h7a1cb2a_0
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.13.1          py3.7_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-lightning         1.9.5                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
requests                  2.28.1           py37h06a4308_0
requests-oauthlib         1.3.1                    pypi_0    pypi
resampy                   0.4.2                    pypi_0    pypi
rich                      13.3.5                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
sentry-sdk                1.23.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.3.5                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.6                      pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.13.1               py37_cu117    pytorch
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.14.1               py37_cu117    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.3.0            py37h06a4308_0
urllib3                   1.26.14          py37h06a4308_0
wandb                     0.15.3                   pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0
xz                        5.2.10               h5eee18b_1
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.5                hc292b87_0

**Comment by liulian233** [comment]
The packages are blow. What should I do?
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
audioread                 3.0.0                    pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.01.10           h06a4308_0
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7        py37h06a4308_0
cffi                      1.15.1           py37h5eee18b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.3                    pypi_0    pypi
cryptography              39.0.1           py37h9ce1e76_0
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
facenet-pytorch           2.5.3                    pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
google-auth               2.18.1                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
idna                      3.4              py37h06a4308_0
imageio                   2.28.1                   pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561
jpeg                      9e                   h5eee18b_1
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lazy-loader               0.2                      pypi_0    pypi
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_0
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.2                h7f8727e_0
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0
librosa                   0.8.1                    pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.0                h6a678d5_2
libunistring              0.9.10               h27cfd23_0
libwebp                   1.2.4                h11a3e52_1
libwebp-base              1.2.4                h5eee18b_1
lightning-utilities       0.8.0                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
metrics                   0.3.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py37h7f8727e_0
mkl_fft                   1.3.1            py37hd3c417c_0
mkl_random                1.2.2            py37h51133e4_0
msgpack                   1.0.5                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
munch                     2.5.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  2.6.3                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.21.5           py37h6c91a56_3
numpy-base                1.21.5           py37ha15fc14_3
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1t               h7f8727e_0
packaging                 23.1                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pathlib2                  2.3.7.post1              pypi_0    pypi
pathspec                  0.5.5                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    9.4.0            py37h6a678d5_0
pip                       22.3.1           py37h06a4308_0
pooch                     1.6.0                    pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.15.1                   pypi_0    pypi
pyopenssl                 23.0.0           py37h06a4308_0
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1                    py37_1
python                    3.7.16               h7a1cb2a_0
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.13.1          py3.7_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-lightning         1.9.5                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
requests                  2.28.1           py37h06a4308_0
requests-oauthlib         1.3.1                    pypi_0    pypi
resampy                   0.4.2                    pypi_0    pypi
rich                      13.3.5                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
sentry-sdk                1.23.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3           py37h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.3.5                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.6                      pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.13.1               py37_cu117    pytorch
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.14.1               py37_cu117    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.3.0            py37h06a4308_0
urllib3                   1.26.14          py37h06a4308_0
wandb                     0.15.3                   pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0
xz                        5.2.10               h5eee18b_1
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.5                hc292b87_0

**Comment by altndrr** [comment]
The Lightning version differs from the one reported in the `pyproject.toml` file. Have you installed the environment using the command `make install` as suggested in the README file? If you did, did you subsequently source the virtual environment created by the make operation before running your command?

**Comment by liulian233** [comment]
Sorry, I didn't, I'll try it now. Thanks a lot.

**Comment by liulian233** [comment]
I've already tried it, and just re-download the required Pytorch-lightning version in the original environment

**Comment by liulian233** [comment]
I've already tried it, and just re-download the required Pytorch-lightning version in the original environment
